### ISSUE TITLE
请问如何使用？

### ISSUE THREAD

**Issue by zhouii** [louphier/iptv#1]
在GitHub搜到很多类似你仓库里`http://192.168.1.1:15104/udp/239.45.3.146:5140`的地址，看起来像是用了同一套方案把电信IPTV电视专网的组播代理出来了？但是都没有找到搭建本地服务器的README教程😭请问下如何在内网搭建这样的服务，相关软件和教程有没有链接能指个路？谢谢

**Comment by louphier** [comment]
上海电信iptv可以参考张大妈上面的《使用openwrt观看上海电信iptv的保姆级教程》这一篇教程，https://post.smzdm.com/p/61886/
